export const ACTIVITY_ENTITY_TYPE = Object.freeze({
  USER: "USER",
  TEAM: "TEAM",
  TASK: "TASK",
  COMMENT: "COMMENT",
  ATTACHMENT: "ATTACHMENT",
  AUTH_SESSION: "AUTH_SESSION",
  PASSWORD_RESET: "PASSWORD_RESET",
});

export const ACTIVITY_ACTION = Object.freeze({
  USER_CREATED: "USER_CREATED",
  USER_UPDATED: "USER_UPDATED",
  USER_STATUS_CHANGED: "USER_STATUS_CHANGED",
  USER_PASSWORD_CHANGED: "USER_PASSWORD_CHANGED",
  TEAM_CREATED: "TEAM_CREATED",
  TEAM_UPDATED: "TEAM_UPDATED",
  TASK_CREATED: "TASK_CREATED",
  TASK_UPDATED: "TASK_UPDATED",
  TASK_REASSIGNED: "TASK_REASSIGNED",
  TASK_STATUS_CHANGED: "TASK_STATUS_CHANGED",
  COMMENT_CREATED: "COMMENT_CREATED",
  COMMENT_UPDATED: "COMMENT_UPDATED",
  COMMENT_DELETED: "COMMENT_DELETED",
  ATTACHMENT_ADDED: "ATTACHMENT_ADDED",
  ATTACHMENT_DELETED: "ATTACHMENT_DELETED",
  LOGIN_SUCCEEDED: "LOGIN_SUCCEEDED",
  TOKEN_REFRESHED: "TOKEN_REFRESHED",
  LOGOUT: "LOGOUT",
  PASSWORD_RESET_ISSUED: "PASSWORD_RESET_ISSUED",
  PASSWORD_RESET_COMPLETED: "PASSWORD_RESET_COMPLETED",
});

export const ACTIVITY_ENTITY_TYPE_VALUES = Object.freeze(
  Object.values(ACTIVITY_ENTITY_TYPE),
);
export const ACTIVITY_ACTION_VALUES = Object.freeze(
  Object.values(ACTIVITY_ACTION),
);
