const NOTIFICATION_TYPE = Object.freeze({
  TASK_ASSIGNED: "TASK_ASSIGNED",
  TASK_REASSIGNED: "TASK_REASSIGNED",
  TASK_UPDATED: "TASK_UPDATED",
  TASK_STATUS_CHANGED: "TASK_STATUS_CHANGED",
  COMMENT_ADDED: "COMMENT_ADDED",
  ATTACHMENT_ADDED: "ATTACHMENT_ADDED",
  TASK_DUE_SOON: "TASK_DUE_SOON",
  TASK_OVERDUE: "TASK_OVERDUE",
});

export const NOTIFICATION_TYPE_VALUES = Object.freeze(
  Object.values(NOTIFICATION_TYPE),
);

export default NOTIFICATION_TYPE;
